/obj/machinery/chemical_dispenser/deluxe
	name = "deluxe drink dispenser"
	desc = "The premium within dispenser for drinks, its made with bluespace technology!"
	icon = 'icons/obj/casino_ch.dmi'
	icon_state = "deluxe_dispenser"
	ui_title = "Deluxe Drink Dispenser"
	accept_drinking = 1
	max_catriges = 90 //Because it keeps getting borked by upstream, now gotta do it with variable until we can make more permanent solution - Jack


/obj/machinery/chemical_dispenser/deluxe
	dispense_reagents = list(
		REAGENT_ID_WATER, REAGENT_ID_ICE, REAGENT_ID_COFFEE, REAGENT_ID_CREAM, REAGENT_ID_TEA, REAGENT_ID_ICETEA, REAGENT_ID_COLA, REAGENT_ID_SPACEMOUNTAINWIND, REAGENT_ID_DRGIBB, REAGENT_ID_SPACEUP, REAGENT_ID_TONIC,
		REAGENT_ID_SODAWATER, REAGENT_ID_LEMONLIME, REAGENT_ID_SUGAR, REAGENT_ID_ORANGEJUICE, REAGENT_ID_LIMEJUICE, REAGENT_ID_WATERMELONJUICE, REAGENT_ID_THIRTEENLOKO, REAGENT_ID_GRAPESODA,
		REAGENT_ID_COFFEE, REAGENT_ID_CAFELATTE, REAGENT_ID_SOYLATTE, REAGENT_ID_HOTCOCO, REAGENT_ID_MILK, REAGENT_ID_CREAM, REAGENT_ID_TEA, REAGENT_ID_WATER, REAGENT_ID_ICE, REAGENT_ID_ORANGEJUICE, REAGENT_ID_LEMONJUICE,
		REAGENT_ID_LIMEJUICE, REAGENT_ID_BERRYJUICE, REAGENT_ID_MINT, REAGENT_ID_LEMONLIME, REAGENT_ID_SUGAR, REAGENT_ID_ORANGEJUICE, REAGENT_ID_LIMEJUICE, REAGENT_ID_SODAWATER,
		REAGENT_ID_TONIC, REAGENT_ID_BEER, REAGENT_ID_KAHLUA, REAGENT_ID_WHISKEY, REAGENT_ID_REDWINE, REAGENT_ID_VODKA, REAGENT_ID_GIN, REAGENT_ID_RUM, REAGENT_ID_TEQUILA, REAGENT_ID_VERMOUTH, REAGENT_ID_COGNAC,
		REAGENT_ID_ALE, REAGENT_ID_MEAD, REAGENT_ID_BITTERS, REAGENT_ID_CHAMPAGNE, REAGENT_ID_SINGULO, REAGENT_ID_DOCTORSDELIGHT, REAGENT_ID_NOTHING, REAGENT_ID_BANANA, REAGENT_ID_HONEY, REAGENT_ID_EGG,
		REAGENT_ID_COCO, REAGENT_ID_CHERRYJELLY, REAGENT_ID_CARROTJUICE, REAGENT_ID_APPLEJUICE, REAGENT_ID_TOMATOJUICE, REAGENT_ID_PEANUTBUTTER, REAGENT_ID_SOYMILK, REAGENT_ID_GRENADINE, REAGENT_ID_GINGERALE, REAGENT_ID_ROYROGERS,
		REAGENT_ID_PATRON, REAGENT_ID_GOLDSCHLAGER, REAGENT_ID_GELATIN, REAGENT_ID_MELONLIQUOR, REAGENT_ID_BLUECURACAO, REAGENT_ID_THIRTEENLOKO, REAGENT_ID_DEADRUM, REAGENT_ID_SAKE, REAGENT_ID_ACIDSPIT,
		REAGENT_ID_AMASEC, REAGENT_ID_BEEPSKYSMASH, REAGENT_ID_ATOMICBOMB, REAGENT_ID_NUKACOLA, REAGENT_ID_THREEMILEISLAND, REAGENT_ID_MANHATTANPROJ, REAGENT_ID_PSILOCYBIN, REAGENT_ID_MOONSHINE,
		REAGENT_ID_SPECIALWHISKEY, REAGENT_ID_UNATHILIQUOR, REAGENT_ID_WINEBRANDY, REAGENT_ID_MATCHALATTE, REAGENT_ID_SNAPS
		)

/obj/machinery/chemical_dispenser/deluxe/full
	spawn_cartridges = list(
			/obj/item/reagent_containers/chem_disp_cartridge/water,
			/obj/item/reagent_containers/chem_disp_cartridge/ice,
			/obj/item/reagent_containers/chem_disp_cartridge/coffee,
			/obj/item/reagent_containers/chem_disp_cartridge/cream,
			/obj/item/reagent_containers/chem_disp_cartridge/tea,
			/obj/item/reagent_containers/chem_disp_cartridge/icetea,
			/obj/item/reagent_containers/chem_disp_cartridge/cola,
			/obj/item/reagent_containers/chem_disp_cartridge/smw,
			/obj/item/reagent_containers/chem_disp_cartridge/dr_gibb,
			/obj/item/reagent_containers/chem_disp_cartridge/spaceup,
			/obj/item/reagent_containers/chem_disp_cartridge/tonic,
			/obj/item/reagent_containers/chem_disp_cartridge/sodawater,
			/obj/item/reagent_containers/chem_disp_cartridge/lemon_lime,
			/obj/item/reagent_containers/chem_disp_cartridge/sugar,
			/obj/item/reagent_containers/chem_disp_cartridge/orange,
			/obj/item/reagent_containers/chem_disp_cartridge/lime,
			/obj/item/reagent_containers/chem_disp_cartridge/watermelon,
			/obj/item/reagent_containers/chem_disp_cartridge/lemon,
			/obj/item/reagent_containers/chem_disp_cartridge/coffee,
			/obj/item/reagent_containers/chem_disp_cartridge/cafe_latte,
			/obj/item/reagent_containers/chem_disp_cartridge/soy_latte,
			/obj/item/reagent_containers/chem_disp_cartridge/hot_coco,
			/obj/item/reagent_containers/chem_disp_cartridge/milk,
			/obj/item/reagent_containers/chem_disp_cartridge/cream,
			/obj/item/reagent_containers/chem_disp_cartridge/tea,
			/obj/item/reagent_containers/chem_disp_cartridge/ice,
			/obj/item/reagent_containers/chem_disp_cartridge/mint,
			/obj/item/reagent_containers/chem_disp_cartridge/orange,
			/obj/item/reagent_containers/chem_disp_cartridge/lemon,
			/obj/item/reagent_containers/chem_disp_cartridge/lime,
			/obj/item/reagent_containers/chem_disp_cartridge/berry,
			/obj/item/reagent_containers/chem_disp_cartridge/lemon_lime,
			/obj/item/reagent_containers/chem_disp_cartridge/sugar,
			/obj/item/reagent_containers/chem_disp_cartridge/orange,
			/obj/item/reagent_containers/chem_disp_cartridge/lime,
			/obj/item/reagent_containers/chem_disp_cartridge/sodawater,
			/obj/item/reagent_containers/chem_disp_cartridge/tonic,
			/obj/item/reagent_containers/chem_disp_cartridge/beer,
			/obj/item/reagent_containers/chem_disp_cartridge/kahlua,
			/obj/item/reagent_containers/chem_disp_cartridge/whiskey,
			/obj/item/reagent_containers/chem_disp_cartridge/redwine,
			/obj/item/reagent_containers/chem_disp_cartridge/vodka,
			/obj/item/reagent_containers/chem_disp_cartridge/gin,
			/obj/item/reagent_containers/chem_disp_cartridge/rum,
			/obj/item/reagent_containers/chem_disp_cartridge/tequila,
			/obj/item/reagent_containers/chem_disp_cartridge/vermouth,
			/obj/item/reagent_containers/chem_disp_cartridge/cognac,
			/obj/item/reagent_containers/chem_disp_cartridge/ale,
			/obj/item/reagent_containers/chem_disp_cartridge/mead,
			/obj/item/reagent_containers/chem_disp_cartridge/champagne,
			/obj/item/reagent_containers/chem_disp_cartridge/grapesoda,
			/obj/item/reagent_containers/chem_disp_cartridge/singulo,
			/obj/item/reagent_containers/chem_disp_cartridge/doctorsdelight,
			/obj/item/reagent_containers/chem_disp_cartridge/nothing,
			/obj/item/reagent_containers/chem_disp_cartridge/banana,
			/obj/item/reagent_containers/chem_disp_cartridge/honey,
			/obj/item/reagent_containers/chem_disp_cartridge/egg,
			/obj/item/reagent_containers/chem_disp_cartridge/coco,
			/obj/item/reagent_containers/chem_disp_cartridge/cherryjelly,
			/obj/item/reagent_containers/chem_disp_cartridge/carrotjuice,
			/obj/item/reagent_containers/chem_disp_cartridge/applejuice,
			/obj/item/reagent_containers/chem_disp_cartridge/tomatojuice,
			/obj/item/reagent_containers/chem_disp_cartridge/soymilk,
			/obj/item/reagent_containers/chem_disp_cartridge/peanutbutter,
			/obj/item/reagent_containers/chem_disp_cartridge/matcha_latte,
			/obj/item/reagent_containers/chem_disp_cartridge/gelatin,
			/obj/item/reagent_containers/chem_disp_cartridge/grenadine,
			/obj/item/reagent_containers/chem_disp_cartridge/gingerale,
			/obj/item/reagent_containers/chem_disp_cartridge/roy_rogers,
			/obj/item/reagent_containers/chem_disp_cartridge/patron,
			/obj/item/reagent_containers/chem_disp_cartridge/goldschlager,
			/obj/item/reagent_containers/chem_disp_cartridge/melonliquor,
			/obj/item/reagent_containers/chem_disp_cartridge/bluecuracao,
			/obj/item/reagent_containers/chem_disp_cartridge/thirteenloko,
			/obj/item/reagent_containers/chem_disp_cartridge/deadrum,
			/obj/item/reagent_containers/chem_disp_cartridge/sake,
			/obj/item/reagent_containers/chem_disp_cartridge/acidspit,
			/obj/item/reagent_containers/chem_disp_cartridge/amasec,
			/obj/item/reagent_containers/chem_disp_cartridge/beepskysmash,
			/obj/item/reagent_containers/chem_disp_cartridge/atomicbomb,
			/obj/item/reagent_containers/chem_disp_cartridge/nuka_cola,
			/obj/item/reagent_containers/chem_disp_cartridge/threemileisland,
			/obj/item/reagent_containers/chem_disp_cartridge/manhattan_proj,
			/obj/item/reagent_containers/chem_disp_cartridge/psilocybin,
			/obj/item/reagent_containers/chem_disp_cartridge/moonshine,
			/obj/item/reagent_containers/chem_disp_cartridge/specialwhiskey,
			/obj/item/reagent_containers/chem_disp_cartridge/unathiliquor,
			/obj/item/reagent_containers/chem_disp_cartridge/winebrandy,
			/obj/item/reagent_containers/chem_disp_cartridge/snaps
			)
