/obj/machinery/chemical_dispenser/deluxe
	name = "deluxe drink dispenser"
	desc = "The premium within dispenser for drinks, its made with bluespace technology!"
	icon = 'icons/obj/casino_ch.dmi'
	icon_state = "deluxe_dispenser"
	ui_title = "Deluxe Drink Dispenser"
	accept_drinking = 1
	max_catriges = 90 //Because it keeps getting borked by upstream, now gotta do it with variable until we can make more permanent solution - Jack


/obj/machinery/chemical_dispenser/deluxe
	dispense_reagents = list(
		"water", "ice", "coffee", "cream", "tea", "icetea", "cola", "spacemountainwind", "dr_gibb", "space_up", "tonic",
		"sodawater", "lemon_lime", "sugar", "orangejuice", "limejuice", "watermelonjuice", "thirteenloko", "grapesoda",
		"coffee", "cafe_latte", "soy_latte", "hot_coco", "milk", "cream", "tea", "ice", "orangejuice", "lemonjuice",
		"limejuice", "berryjuice", "mint", "lemon_lime", "sugar", "orangejuice", "limejuice", "sodawater",
		"tonic", "beer", "kahlua", "whiskey", "redwine", "vodka", "gin", "rum", "tequilla", "vermouth", "cognac",
		"ale", "mead", "bitters", "champagne", "singulo", "doctorsdelight", "nothing", "banana", "honey", "egg",
		"coco", "cherryjelly", "carrotjuice", "applejuice", "tomatojuice", "peanutbutter", "soymilk", "grenadine", "gingerale", "roy_rogers",
		"patron", "goldschlager", "gelatin", "melonliquor", "bluecuracao", "thirteenloko", "deadrum", "sake", "acidspit",
		"amasec", "beepskysmash", "atomicbomb", "nuka_cola", "threemileisland", "manhattan_proj", "psilocybin", "moonshine",
		"specialwhiskey", "unathiliquor", "winebrandy", "matcha_latte", "snaps"
		)

/obj/machinery/chemical_dispenser/deluxe/full
	spawn_cartridges = list(
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/water,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/ice,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/coffee,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/cream,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/tea,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/icetea,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/cola,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/smw,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/dr_gibb,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/spaceup,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/tonic,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/sodawater,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/lemon_lime,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/sugar,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/orange,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/lime,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/watermelon,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/lemon,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/coffee,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/cafe_latte,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/soy_latte,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/hot_coco,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/milk,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/cream,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/tea,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/ice,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/mint,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/orange,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/lemon,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/lime,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/berry,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/lemon_lime,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/sugar,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/orange,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/lime,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/sodawater,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/tonic,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/beer,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/kahlua,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/whiskey,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/redwine,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/vodka,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/gin,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/rum,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/tequila,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/vermouth,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/cognac,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/ale,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/mead,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/champagne,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/grapesoda,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/singulo,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/doctorsdelight,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/nothing,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/banana,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/honey,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/egg,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/coco,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/cherryjelly,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/carrotjuice,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/applejuice,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/tomatojuice,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/soymilk,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/peanutbutter,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/matcha_latte,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/gelatin,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/grenadine,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/gingerale,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/roy_rogers,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/patron,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/goldschlager,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/melonliquor,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/bluecuracao,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/thirteenloko,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/deadrum,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/sake,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/acidspit,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/amasec,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/beepskysmash,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/atomicbomb,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/nuka_cola,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/threemileisland,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/manhattan_proj,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/psilocybin,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/moonshine,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/specialwhiskey,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/unathiliquor,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/winebrandy,
			/obj/item/weapon/reagent_containers/chem_disp_cartridge/snaps
			)
