//Replace old magazine with new
/obj/item/ammo_magazine/Initialize(mapload)
	. = ..()
	var/replacement_type = magazine_overrides[type]
	if(replacement_type)
		new replacement_type(loc)
		return INITIALIZE_HINT_QDEL
	. = ..()


//Override attackby to allow magazine to magazine transfer
/obj/item/ammo_magazine/attackby(obj/item/W as obj, mob/user as mob)
	if(istype(W, /obj/item/ammo_casing))
		var/obj/item/ammo_casing/C = W
		if(C.caliber != caliber)
			to_chat(user, span_warning("[C] does not fit into [src]."))
			return
		if(stored_ammo.len >= max_ammo)
			to_chat(user, span_warning("[src] is full!"))
			return
		user.remove_from_mob(C)
		C.forceMove(src)
		stored_ammo.Add(C)
		update_icon()
	if(istype(W, /obj/item/ammo_magazine))
		var/obj/item/ammo_magazine/L = W
		if(L.caliber != caliber)
			to_chat(user, span_warning("The ammo in [L] does not fit into [src]."))
			return
		if(!L.stored_ammo.len)
			to_chat(user, span_warning("There's no more ammo [L]!"))
			return
		if(stored_ammo.len >= max_ammo)
			to_chat(user, span_warning("[src] is full!"))
			return
		while(L.stored_ammo.len && stored_ammo.len < max_ammo)
			var/obj/item/ammo_casing/AC = L.stored_ammo[1] //select the next casing.
			L.stored_ammo -= AC //Remove this casing from loaded list of the clip.
			AC.forceMove(src)
			stored_ammo.Insert(1, AC) //add it to the head of our magazine's list
		L.update_icon()
	else
		return //Don't play sound if nothing actually happens xD
	playsound(src, 'sound/weapons/flipblade.ogg', 50, 1)
	update_icon()

//big boy list
var/global/list/magazine_overrides = list(
	/obj/item/ammo_magazine/m9mmt = /obj/item/ammo_magazine/smg,
	/obj/item/ammo_magazine/m9mm/compact = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m9mm = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m762 = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/m9mmAdvanced = /obj/item/ammo_magazine/smg,
	/obj/item/ammo_magazine/m545 = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/m545saw = /obj/item/ammo_magazine/medium_box,
	/obj/item/ammo_magazine/m45uzi = /obj/item/ammo_magazine/smg,
	/obj/item/ammo_magazine/m45tommy = /obj/item/ammo_magazine/smg,
	/obj/item/ammo_magazine/m45tommydrum = /obj/item/ammo_magazine/smg_drum,
	/obj/item/ammo_magazine/m762/ext = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/m10mm = /obj/item/ammo_magazine/smg,
	/obj/item/ammo_magazine/m95 = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/mtg = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/mg42 = /obj/item/ammo_magazine/medium_box,
	/obj/item/ammo_magazine/mp5mag = /obj/item/ammo_magazine/smg,
	/obj/item/ammo_magazine/asval = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/akm = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/ak74 = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/m762svd = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/m16 = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/ar10 = /obj/item/ammo_magazine/medium_small,
	/obj/item/ammo_magazine/m41 = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/t12 = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/fal = /obj/item/ammo_magazine/medium_small,
	/obj/item/ammo_magazine/type901 = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/awp = /obj/item/ammo_magazine/large,
	/obj/item/ammo_magazine/hectate = /obj/item/ammo_magazine/large,
	/obj/item/ammo_magazine/plamya = /obj/item/ammo_magazine/medium_drum,
	/obj/item/ammo_magazine/ppsh = /obj/item/ammo_magazine/smg_drum,
	/obj/item/ammo_magazine/pitchmag = /obj/item/ammo_magazine/smg,
	/obj/item/ammo_magazine/molniya = /obj/item/ammo_magazine/medium_box,
	/obj/item/ammo_magazine/pkm = /obj/item/ammo_magazine/medium_box,
	/obj/item/ammo_magazine/rpd = /obj/item/ammo_magazine/medium_box,
	/obj/item/ammo_magazine/kord = /obj/item/ammo_magazine/large_box,
	/obj/item/ammo_magazine/ssp4 = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/sam48 = /obj/item/ammo_magazine/clip/medium,
	/obj/item/ammo_magazine/m5mmcaseless = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/m45 = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m44 = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m9mm/luger = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m38 = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m10mm/pistol = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m44/rubber = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m2024 = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m762enbloc = /obj/item/ammo_magazine/clip/medium,
	/obj/item/ammo_magazine/makarov = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/tp23s = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/tp23 = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m9mm/compact/flash = /obj/item/ammo_magazine/pistol/flash,
	/obj/item/ammo_magazine/m9mmt/rubber = /obj/item/ammo_magazine/smg/rubber,
	/obj/item/ammo_magazine/m10mm/rubber = /obj/item/ammo_magazine/smg/rubber,
	/obj/item/ammo_magazine/ak74/plum = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/m16/patriot = /obj/item/ammo_magazine/medium_drum,
	/obj/item/ammo_magazine/akm/drum = /obj/item/ammo_magazine/medium_drum,
	/obj/item/ammo_magazine/m45/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/m45/flash = /obj/item/ammo_magazine/pistol/flash,
	/obj/item/ammo_magazine/m9mm/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/m9mm/large = /obj/item/ammo_magazine/pistol_large,
	/obj/item/ammo_magazine/m9mm/large/preban = /obj/item/ammo_magazine/pistol_large,
	/obj/item/ammo_magazine/m9mm/large/preban/hp = /obj/item/ammo_magazine/pistol_large/hp,
	/obj/item/ammo_magazine/m9mm/vp70 = /obj/item/ammo_magazine/smg,
	/obj/item/ammo_magazine/tp23/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/ammo_box/b357 = /obj/item/ammo_magazine/ammo_box/small,
	/obj/item/ammo_magazine/ammo_box/b38 = /obj/item/ammo_magazine/ammo_box/small,
	/obj/item/ammo_magazine/ammo_box/b10mm = /obj/item/ammo_magazine/ammo_box/small,
	/obj/item/ammo_magazine/ammo_box/b44 = /obj/item/ammo_magazine/ammo_box/small,
	/obj/item/ammo_magazine/ammo_box/b45 = /obj/item/ammo_magazine/ammo_box/small,
	///obj/item/ammo_magazine/ammo_box/b145 = /obj/item/ammo_magazine/ammo_box/large, Seperation of 14.5
	///obj/item/ammo_magazine/ammo_box/b145/highvel = /obj/item/ammo_magazine/ammo_box/large/ap,
	/obj/item/ammo_magazine/ammo_box/b762 = /obj/item/ammo_magazine/ammo_box/medium,
	/obj/item/ammo_magazine/ammo_box/b545 = /obj/item/ammo_magazine/ammo_box/medium,
	/obj/item/ammo_magazine/ammo_box/b545/large = /obj/item/ammo_magazine/ammo_box/medium/large,
	/obj/item/ammo_magazine/s357 = /obj/item/ammo_magazine/speedloader_six,
	/obj/item/ammo_magazine/s38 = /obj/item/ammo_magazine/speedloader_eight,
	/obj/item/ammo_magazine/clip/sks = /obj/item/ammo_magazine/clip/medium,
	/obj/item/ammo_magazine/clip/mosin = /obj/item/ammo_magazine/clip/medium,
	/obj/item/ammo_magazine/clip/c762 = /obj/item/ammo_magazine/clip/medium,
	/obj/item/ammo_magazine/clip/c545 = /obj/item/ammo_magazine/clip/medium,
	/obj/item/ammo_magazine/s44 = /obj/item/ammo_magazine/speedloader_six,
	/obj/item/ammo_magazine/s45 = /obj/item/ammo_magazine/speedloader_six,
	/obj/item/ammo_magazine/s45lc = /obj/item/ammo_magazine/speedloader_six,
	/obj/item/ammo_magazine/m545/small = /obj/item/ammo_magazine/medium_small,
	/obj/item/ammo_magazine/mglock9mm = /obj/item/ammo_magazine/pistol_large,
	/obj/item/ammo_magazine/ammo_box/b357/rubber = /obj/item/ammo_magazine/ammo_box/small/rubber,
	/obj/item/ammo_magazine/ammo_box/b38/rubber = /obj/item/ammo_magazine/ammo_box/small/rubber,
	/obj/item/ammo_magazine/ammo_box/b10mm/practice = /obj/item/ammo_magazine/ammo_box/small/practice,
	/obj/item/ammo_magazine/ammo_box/b10mm/rubber = /obj/item/ammo_magazine/ammo_box/small/rubber,
	/obj/item/ammo_magazine/ammo_box/b10mm/emp = /obj/item/ammo_magazine/ammo_box/small/emp,
	/obj/item/ammo_magazine/ammo_box/b44/rubber = /obj/item/ammo_magazine/ammo_box/small/rubber,
	/obj/item/ammo_magazine/ammo_box/b45/practice = /obj/item/ammo_magazine/ammo_box/small/practice,
	/obj/item/ammo_magazine/ammo_box/b45/ap = /obj/item/ammo_magazine/ammo_box/small/ap,
	/obj/item/ammo_magazine/ammo_box/b45/hp = /obj/item/ammo_magazine/ammo_box/small/hp,
	/obj/item/ammo_magazine/ammo_box/b45/rubber = /obj/item/ammo_magazine/ammo_box/small/rubber,
	/obj/item/ammo_magazine/ammo_box/b45/emp = /obj/item/ammo_magazine/ammo_box/small/emp,
	/obj/item/ammo_magazine/ammo_box/b762/hp = /obj/item/ammo_magazine/ammo_box/medium/hp,
	/obj/item/ammo_magazine/ammo_box/b762/ap = /obj/item/ammo_magazine/ammo_box/medium/ap,
	/obj/item/ammo_magazine/ammo_box/b762/practice = /obj/item/ammo_magazine/ammo_box/medium/practice,
	/obj/item/ammo_magazine/ammo_box/b762/hunter = /obj/item/ammo_magazine/ammo_box/medium/hunter,
	/obj/item/ammo_magazine/ammo_box/b545/ap = /obj/item/ammo_magazine/ammo_box/medium/ap,
	/obj/item/ammo_magazine/ammo_box/b545/hp = /obj/item/ammo_magazine/ammo_box/medium/hp,
	/obj/item/ammo_magazine/ammo_box/b545/practice = /obj/item/ammo_magazine/ammo_box/medium/practice,
	/obj/item/ammo_magazine/ammo_box/b545/hunter = /obj/item/ammo_magazine/ammo_box/medium/hunter,
	/obj/item/ammo_magazine/ammo_box/b545/large/ap = /obj/item/ammo_magazine/ammo_box/medium/large/ap,
	/obj/item/ammo_magazine/ammo_box/b545/large/hp = /obj/item/ammo_magazine/ammo_box/medium/large/hp,
	/obj/item/ammo_magazine/ammo_box/b545/large/practice = /obj/item/ammo_magazine/ammo_box/medium/large/practice,
	/obj/item/ammo_magazine/ammo_box/b545/large/hunter = /obj/item/ammo_magazine/ammo_box/medium/large/hunter,
	/obj/item/ammo_magazine/s357/rubber = /obj/item/ammo_magazine/speedloader_six/rubber,
	/obj/item/ammo_magazine/s357/flash = /obj/item/ammo_magazine/speedloader_six/flash,
	/obj/item/ammo_magazine/s38/rubber = /obj/item/ammo_magazine/speedloader_eight/rubber,
	/obj/item/ammo_magazine/s38/emp = /obj/item/ammo_magazine/speedloader_eight/emp,
	/obj/item/ammo_magazine/m38/makarov = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m38/giskard = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/m45/empty = /obj/item/ammo_magazine/pistol/empty,
	/obj/item/ammo_magazine/m45/practice = /obj/item/ammo_magazine/pistol/practice,
	/obj/item/ammo_magazine/m45/ap = /obj/item/ammo_magazine/pistol/ap,
	/obj/item/ammo_magazine/m45/hp = /obj/item/ammo_magazine/pistol/hp,
	/obj/item/ammo_magazine/m45uzi/empty = /obj/item/ammo_magazine/smg/empty,
	/obj/item/ammo_magazine/m45tommy/ap = /obj/item/ammo_magazine/smg/ap,
	/obj/item/ammo_magazine/m45tommy/empty = /obj/item/ammo_magazine/smg/empty,
	/obj/item/ammo_magazine/m45tommydrum/empty = /obj/item/ammo_magazine/smg_drum/empty,
	/obj/item/ammo_magazine/m45tommydrum/ap = /obj/item/ammo_magazine/smg_drum/ap,
	/obj/item/ammo_magazine/clip/c545/ap = /obj/item/ammo_magazine/clip/medium/ap,
	/obj/item/ammo_magazine/clip/c545/hunter = /obj/item/ammo_magazine/clip/medium/hunter,
	/obj/item/ammo_magazine/clip/c545/practice = /obj/item/ammo_magazine/clip/medium/practice,
	/obj/item/ammo_magazine/clip/c762/ap = /obj/item/ammo_magazine/clip/medium/ap,
	/obj/item/ammo_magazine/clip/c762/practice = /obj/item/ammo_magazine/clip/medium/practice,
	/obj/item/ammo_magazine/clip/c762/hunter = /obj/item/ammo_magazine/clip/medium/hunter,
	/obj/item/ammo_magazine/clip/sks/ap = /obj/item/ammo_magazine/clip/medium/ap,
	/obj/item/ammo_magazine/clip/mosin/ap = /obj/item/ammo_magazine/clip/medium/ap,
	/obj/item/ammo_magazine/s45/rubber = /obj/item/ammo_magazine/speedloader_six/rubber,
	/obj/item/ammo_magazine/s45/practice = /obj/item/ammo_magazine/speedloader_six/practice,
	/obj/item/ammo_magazine/s45/flash = /obj/item/ammo_magazine/speedloader_six/flash,
	/obj/item/ammo_magazine/s45/ap = /obj/item/ammo_magazine/speedloader_six/ap,
	/obj/item/ammo_magazine/m5mmcaseless/empty = /obj/item/ammo_magazine/medium/empty,
	/obj/item/ammo_magazine/m9mm/empty = /obj/item/ammo_magazine/pistol/empty,
	/obj/item/ammo_magazine/m9mm/flash = /obj/item/ammo_magazine/pistol/flash,
	/obj/item/ammo_magazine/m9mm/practice = /obj/item/ammo_magazine/pistol/practice,
	/obj/item/ammo_magazine/m9mm/large/empty = /obj/item/ammo_magazine/pistol_large/empty,
	/obj/item/ammo_magazine/m9mm/compact/empty = /obj/item/ammo_magazine/pistol/empty,
	/obj/item/ammo_magazine/m9mm/compact/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/m9mm/compact/practice = /obj/item/ammo_magazine/pistol/practice,
	/obj/item/ammo_magazine/m9mm/luger/empty = /obj/item/ammo_magazine/pistol/empty,
	/obj/item/ammo_magazine/m9mm/luger/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/m9mm/vp70/ap = /obj/item/ammo_magazine/smg/ap,
	/obj/item/ammo_magazine/m9mm/vp70/hp = /obj/item/ammo_magazine/smg/hp,
	/obj/item/ammo_magazine/m9mm/vp70/rubber = /obj/item/ammo_magazine/smg/rubber,
	/obj/item/ammo_magazine/m9mm/vp70/flash = /obj/item/ammo_magazine/smg/flash,
	/obj/item/ammo_magazine/m9mmt/empty = /obj/item/ammo_magazine/smg/empty,
	/obj/item/ammo_magazine/m9mmt/flash = /obj/item/ammo_magazine/smg/flash,
	/obj/item/ammo_magazine/m9mmt/practice = /obj/item/ammo_magazine/smg/practice,
	/obj/item/ammo_magazine/m9mmt/ap = /obj/item/ammo_magazine/smg/ap,
	/obj/item/ammo_magazine/m9mmAdvanced/ap = /obj/item/ammo_magazine/smg/ap,
	/obj/item/ammo_magazine/m9mmAdvanced/empty = /obj/item/ammo_magazine/smg/empty,
	/obj/item/ammo_magazine/m10mm/empty = /obj/item/ammo_magazine/smg/empty,
	/obj/item/ammo_magazine/m10mm/practice = /obj/item/ammo_magazine/smg/practice,
	/obj/item/ammo_magazine/m10mm/emp = /obj/item/ammo_magazine/smg/emp,
	/obj/item/ammo_magazine/m10mm/pistol/practice = /obj/item/ammo_magazine/pistol/practice,
	/obj/item/ammo_magazine/m10mm/pistol/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/m10mm/pistol/emp = /obj/item/ammo_magazine/pistol/emp,
	/obj/item/ammo_magazine/m10mm/pistol/empty = /obj/item/ammo_magazine/pistol/empty,
	/obj/item/ammo_magazine/m10mm/ap = /obj/item/ammo_magazine/smg/ap,
	/obj/item/ammo_magazine/m10mm/hp = /obj/item/ammo_magazine/smg/hp,
	/obj/item/ammo_magazine/m545/empty = /obj/item/ammo_magazine/medium/empty,
	/obj/item/ammo_magazine/m545/practice = /obj/item/ammo_magazine/medium/practice,
	/obj/item/ammo_magazine/m545/ap = /obj/item/ammo_magazine/medium/ap,
	/obj/item/ammo_magazine/m545/hunter = /obj/item/ammo_magazine/medium/hunter,
	/obj/item/ammo_magazine/m545/ext = /obj/item/ammo_magazine/medium,
	/obj/item/ammo_magazine/m545/small/empty = /obj/item/ammo_magazine/medium_small/empty,
	/obj/item/ammo_magazine/m545/small/practice = /obj/item/ammo_magazine/medium_small/practice,
	/obj/item/ammo_magazine/m545/small/ap = /obj/item/ammo_magazine/medium_small/ap,
	/obj/item/ammo_magazine/m545/small/hunter = /obj/item/ammo_magazine/medium_small/hunter,
	/obj/item/ammo_magazine/m545saw/empty = /obj/item/ammo_magazine/medium_box/empty,
	/obj/item/ammo_magazine/m545saw/ap = /obj/item/ammo_magazine/medium_box/ap,
	/obj/item/ammo_magazine/m545saw/hunter = /obj/item/ammo_magazine/medium_box,
	/obj/item/ammo_magazine/m44/empty = /obj/item/ammo_magazine/pistol/empty,
	/obj/item/ammo_magazine/s44/rubber = /obj/item/ammo_magazine/speedloader_six/rubber,
	/obj/item/ammo_magazine/m762/empty = /obj/item/ammo_magazine/medium/empty,
	/obj/item/ammo_magazine/m762/ap = /obj/item/ammo_magazine/medium/ap,
	/obj/item/ammo_magazine/m762/ext/empty = /obj/item/ammo_magazine/medium/empty,
	/obj/item/ammo_magazine/m762/ext/ap = /obj/item/ammo_magazine/medium/ap,
	/obj/item/ammo_magazine/m762enbloc/ap = /obj/item/ammo_magazine/clip/medium/ap,
	/obj/item/ammo_magazine/m762enbloc/empty = /obj/item/ammo_magazine/clip/medium/empty,
	/obj/item/ammo_magazine/m762svd/empty = /obj/item/ammo_magazine/medium/empty,
	/obj/item/ammo_magazine/m762svd/ap = /obj/item/ammo_magazine/medium/ap,
	/obj/item/ammo_magazine/m2024/empty = /obj/item/ammo_magazine/pistol/empty,
	/obj/item/ammo_magazine/m2024/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/m2024/practice = /obj/item/ammo_magazine/pistol/practice,
	/obj/item/ammo_magazine/m2024/flash = /obj/item/ammo_magazine/pistol/flash,
	/obj/item/ammo_magazine/m2024/ap = /obj/item/ammo_magazine/pistol/ap,
	/obj/item/ammo_magazine/mglock9mm/empty = /obj/item/ammo_magazine/pistol_large/empty,
	/obj/item/ammo_magazine/mglock9mm/flash = /obj/item/ammo_magazine/pistol_large/flash,
	/obj/item/ammo_magazine/mglock9mm/rubber = /obj/item/ammo_magazine/pistol_large/rubber,
	/obj/item/ammo_magazine/mglock9mm/practice = /obj/item/ammo_magazine/pistol_large/practice,
	/obj/item/ammo_magazine/mg42/empty = /obj/item/ammo_magazine/medium_box/empty,
	/obj/item/ammo_magazine/mp5mag/ap = /obj/item/ammo_magazine/smg/ap,
	/obj/item/ammo_magazine/mp5mag/hp = /obj/item/ammo_magazine/smg/hp,
	/obj/item/ammo_magazine/mp5mag/rubber = /obj/item/ammo_magazine/smg/rubber,
	/obj/item/ammo_magazine/pitchmag/rubber = /obj/item/ammo_magazine/smg/rubber,
	/obj/item/ammo_magazine/asval/ap = /obj/item/ammo_magazine/medium/ap,
	/obj/item/ammo_magazine/asval/rubber = /obj/item/ammo_magazine/medium/rubber,
	/obj/item/ammo_magazine/akm/ap = /obj/item/ammo_magazine/medium/ap,
	/obj/item/ammo_magazine/akm/hp = /obj/item/ammo_magazine/medium/hp,
	/obj/item/ammo_magazine/akm/rubber = /obj/item/ammo_magazine/medium/rubber,
	/obj/item/ammo_magazine/akm/drum/ap = /obj/item/ammo_magazine/medium_drum/ap,
	/obj/item/ammo_magazine/ak74/ap = /obj/item/ammo_magazine/medium/ap,
	/obj/item/ammo_magazine/ak74/hp = /obj/item/ammo_magazine/medium/hp,
	/obj/item/ammo_magazine/ak74/rubber = /obj/item/ammo_magazine/medium/rubber,
	/obj/item/ammo_magazine/ak74/plum/rubber = /obj/item/ammo_magazine/medium/rubber,
	/obj/item/ammo_magazine/m16/ap = /obj/item/ammo_magazine/medium/ap,
	/obj/item/ammo_magazine/m16/rubber = /obj/item/ammo_magazine/medium/rubber,
	/obj/item/ammo_magazine/m16/hp = /obj/item/ammo_magazine/medium/hp,
	/obj/item/ammo_magazine/m41/rubber = /obj/item/ammo_magazine/medium/rubber,
	/obj/item/ammo_magazine/type901/ap = /obj/item/ammo_magazine/medium/ap,
	/obj/item/ammo_magazine/ar10/ap = /obj/item/ammo_magazine/medium_small/ap,
	/obj/item/ammo_magazine/fal/ap = /obj/item/ammo_magazine/medium_small/ap,
	/obj/item/ammo_magazine/awp/ap = /obj/item/ammo_magazine/large/ap,
	/obj/item/ammo_magazine/hectate/ap = /obj/item/ammo_magazine/large/ap,
	/obj/item/ammo_magazine/plamya/ap = /obj/item/ammo_magazine/medium_drum/ap,
	/obj/item/ammo_magazine/plamya/rubber = /obj/item/ammo_magazine/medium_drum/rubber,
	/obj/item/ammo_magazine/molniya/ap = /obj/item/ammo_magazine/medium_box/ap,
	/obj/item/ammo_magazine/pkm/ap = /obj/item/ammo_magazine/medium_box/ap,
	/obj/item/ammo_magazine/rpd/ap = /obj/item/ammo_magazine/medium_box/ap,
	/obj/item/ammo_magazine/ssp4/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/makarov/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/tp23s/rubber = /obj/item/ammo_magazine/pistol/rubber,
	/obj/item/ammo_magazine/tp23s/highpower = /obj/item/ammo_magazine/pistol,
	/obj/item/ammo_magazine/tp23/flash = /obj/item/ammo_magazine/pistol/flash,
	/obj/item/ammo_magazine/tp23/hp = /obj/item/ammo_magazine/pistol/hp,
	/obj/item/ammo_magazine/tp23/ap = /obj/item/ammo_magazine/pistol/ap,
	/obj/item/ammo_magazine/tp23/emp = /obj/item/ammo_magazine/pistol/emp,
	/obj/item/ammo_magazine/s45lc/rubber = /obj/item/ammo_magazine/speedloader_six/rubber,
	/obj/item/ammo_magazine/s45lc/rifle = /obj/item/ammo_magazine/speedloader_six,
	/obj/item/ammo_magazine/mtg/empty = /obj/item/ammo_magazine/medium/empty,
	/obj/item/ammo_magazine/m95/empty = /obj/item/ammo_magazine/medium/empty,
)
