/mob/living/simple_mob/mechanical/mecha/eclipse
	health = 875
	maxHealth = 875
	faction = FACTION_ECLIPSE
	icon = 'modular_chomp/icons/mob/eclipse.dmi'
	has_repair_droid = TRUE
	ai_holder_type = /datum/ai_holder/simple_mob/intentional/three_phases
	armor = list(melee = 50, bullet = 50, laser = 50, energy = 50, bomb = 50, bio = 100, rad = 100)
	armor_soak = list(melee = 0, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 0, rad = 0)
	special_attack_min_range = 1
	special_attack_max_range = 7
	special_attack_cooldown = 10 //This things attack soley via speical attacks hence basically no cooldown
	grab_resist = 100
	shock_resist = -0.2
	var/specialattackprojectile = /obj/item/projectile/energy/phase/bolt

/mob/living/simple_mob/mechanical/mecha/eclipse/do_special_attack(atom/A)
	upfour_leftfour(A)
	upfour_leftthree(A)
	upfour_lefttwo(A)
	upfour_leftone(A)
	upfour(A)
	upfour_rightone(A)
	upfour_righttwo(A)
	upfour_rightthree(A)
	upfour_rightfour(A)
	upthree_rightfour(A)
	uptwo_rightfour(A)
	upone_rightfour(A)
	rightfour(A)
	downone_rightfour(A)
	downtwo_rightfour(A)
	downthree_rightfour(A)
	downfour_rightfour(A)
	downfour_rightthree(A)
	downfour_righttwo(A)
	downfour_rightone(A)
	downfour(A)
	downfour_leftone(A)
	downfour_lefttwo(A)
	downfour_leftthree(A)
	downfour_leftfour(A)
	downthree_leftfour(A)
	downtwo_leftfour(A)
	downone_leftfour(A)
	leftfour(A)
	upone_leftfour(A)
	uptwo_leftfour(A)
	upthree_leftfour(A)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upfour_leftfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+4, src.y+4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upfour_leftthree(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+3, src.y+4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upfour_lefttwo(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+2, src.y+4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upfour_leftone(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+1, src.y+4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x, src.y+4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upfour_rightone(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-1, src.y+4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upfour_righttwo(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-2, src.y+4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upfour_rightthree(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-3, src.y+4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upfour_rightfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-4, src.y+4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upthree_rightfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-4, src.y+3, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/uptwo_rightfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-4, src.y+2, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upone_rightfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-4, src.y+1, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rightfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-4, src.y, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downone_rightfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-4, src.y-1, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downtwo_rightfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-4, src.y-2, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downthree_rightfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-4, src.y-3, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downfour_rightfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-4, src.y-4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downfour_rightthree(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-3, src.y-4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downfour_righttwo(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-2, src.y-4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downfour_rightone(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x-1, src.y-4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x, src.y-4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downfour_leftone(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+1, src.y-4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downfour_lefttwo(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+2, src.y-4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downfour_leftthree(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+3, src.y-4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downfour_leftfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+4, src.y-4, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downthree_leftfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+4, src.y-3, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downtwo_leftfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+4, src.y-2, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/downone_leftfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+4, src.y-1, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/leftfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+4, src.y, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upone_leftfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+4, src.y+1, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/uptwo_leftfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+4, src.y+2, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/upthree_leftfour(atom/target)
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+4, src.y+3, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

/datum/ai_holder/simple_mob/intentional/three_phases
	use_astar = TRUE
	var/closest_desired_distance = 4

/datum/ai_holder/simple_mob/intentional/three_phases/on_engagement(atom/A)
	if(get_dist(holder, A) > closest_desired_distance)
		holder.IMove(get_step_towards(holder, A))

/datum/ai_holder/simple_mob/intentional/three_phases/pre_special_attack(atom/A)
	if(isliving(A))
		if((holder.health / holder.getMaxHealth()) <= 0.35) //Phase three!
			holder.a_intent = I_DISARM

		else if((holder.health / holder.getMaxHealth()) <= 0.7) //Phase two
			holder.a_intent = I_GRAB

		else
			holder.a_intent = I_HURT

//Each mecha has a strange defense mechanism.
//High defense at the start that falters the more the battle goes on
/mob/living/simple_mob/mechanical/mecha/eclipse/antipersonal_unit //Melts folks with lasers
	specialattackprojectile = /obj/item/projectile/beam/midlaser
	armor = list(melee = 90, bullet = 90, laser = 90, energy = 90, bomb = 90, bio = 100, rad = 100)
	damage_threshold = 0 //So the wierd armor mechanic works
	icon_state = "gygax_adv"

/mob/living/simple_mob/mechanical/mecha/eclipse/antipersonal_unit/updatehealth()
	. = ..()

	if(health < maxHealth*0.3)
		armor = list(melee = 0, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 100, rad = 100)
	else if(health < maxHealth*0.6)
		armor = list(melee = 30, bullet = 30, laser = 30, energy = 30, bomb = 30, bio = 100, rad = 100)
	else if (health < maxHealth*0.9)
		armor = list(melee = 60, bullet = 60, laser = 60, energy = 50, bomb = 60, bio = 100, rad = 100)

/mob/living/simple_mob/mechanical/mecha/eclipse/antipersonal_unit/do_special_attack(atom/A)
	. = TRUE // So we don't fire a bolt as well.
	switch(a_intent)
		if(I_DISARM) // Phase 3
			phase_three(A)
		if(I_HURT) // Phase 1
			phase_one(A)
		if(I_GRAB) // Phase 2
			phase_two(A)

/mob/living/simple_mob/mechanical/mecha/eclipse/antipersonal_unit/proc/phase_one(atom/target) //Basic pattern whilst the defense is high
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	sleep(15)
	upfour(target)
	downfour(target)
	rightfour(target)
	leftfour(target)
	sleep(15)
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	sleep(15)
	upfour(target)
	downfour(target)
	rightfour(target)
	leftfour(target)
	sleep(15)
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	upfour(target)
	downfour(target)
	rightfour(target)
	leftfour(target)
	sleep(15)

/mob/living/simple_mob/mechanical/mecha/eclipse/antipersonal_unit/proc/phase_two(atom/target) //SPIIIIN TO WIN
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	sleep(10)
	upfour_leftthree(target)
	upthree_rightfour(target)
	downfour_rightthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour_lefttwo(target)
	uptwo_rightfour(target)
	downfour_righttwo(target)
	downtwo_leftfour(target)
	sleep(10)
	upfour_leftone(target)
	upone_rightfour(target)
	downfour_rightone(target)
	downone_leftfour(target)
	sleep(10)//
	upfour(target)
	rightfour(target)
	downfour(target)
	leftfour(target)
	sleep(10)
	upfour_rightone(target)
	downone_rightfour(target)
	downfour_leftone(target)
	upone_leftfour(target)
	sleep(10)
	upfour_righttwo(target)
	downtwo_rightfour(target)
	downfour_lefttwo(target)
	uptwo_leftfour(target)
	sleep(10)
	upfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftthree(target)
	upthree_leftfour(target)
	sleep(10)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	upfour_leftfour(target)
	sleep(10) //Now we reverse
	upfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftthree(target)
	upthree_leftfour(target)
	sleep(10)
	upfour_righttwo(target)
	downtwo_rightfour(target)
	downfour_lefttwo(target)
	uptwo_leftfour(target)
	sleep(10)
	upfour_rightone(target)
	downone_rightfour(target)
	downfour_leftone(target)
	upone_leftfour(target)
	sleep(10)
	upfour(target)
	rightfour(target)
	downfour(target)
	leftfour(target)
	sleep(10)
	upfour_leftone(target)
	upone_rightfour(target)
	downfour_rightone(target)
	downone_leftfour(target)
	sleep(10)
	upfour_lefttwo(target)
	uptwo_rightfour(target)
	downfour_righttwo(target)
	downtwo_leftfour(target)
	sleep(10)
	upfour_leftthree(target)
	upthree_rightfour(target)
	downfour_rightthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)


/mob/living/simple_mob/mechanical/mecha/eclipse/antipersonal_unit/proc/phase_three(atom/target) //The strangest pattern but a last stand at 0 defense.
	upfour_leftfour(target)
	sleep(5)
	downfour_rightfour(target)
	sleep(5)
	upfour_leftfour(target)
	sleep(5)
	downfour_leftfour(target)
	sleep(5)
	upfour_lefttwo(target)
	sleep(5)
	downfour_righttwo(target)
	sleep(5)
	upfour_lefttwo(target)
	sleep(5)
	downfour_lefttwo(target)
	sleep(5)
	uptwo_leftfour(target)
	sleep(5)
	downtwo_rightfour(target)
	sleep(5)
	uptwo_leftfour(target)
	sleep(5)
	downtwo_leftfour(target)
	sleep(5)
	upfour_leftone(target)
	sleep(5)
	downfour_rightone(target)
	sleep(5)
	upfour_leftone(target)
	sleep(5)
	downfour_leftone(target)
	sleep(5)
	upone_leftfour(target)
	sleep(5)
	downone_rightfour(target)
	sleep(5)
	upone_leftfour(target)
	sleep(5)
	downone_leftfour(target)
	sleep(5)
	upfour_leftthree(target)
	sleep(5)
	downfour_rightthree(target)
	sleep(5)
	upfour_leftthree(target)
	sleep(5)
	downfour_leftthree(target)
	sleep(5)
	upthree_leftfour(target)
	sleep(5)
	downthree_rightfour(target)
	sleep(5)
	upthree_leftfour(target)
	sleep(5)
	downthree_leftfour(target)
	sleep(5)
	upfour(target)
	sleep(5)
	rightfour(target)
	sleep(5)
	leftfour(target)
	sleep(5)
	downfour(target)

//Nigh unbreakable defenses except during certian attack phases.
/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard //Explosive death
	specialattackprojectile = /obj/item/projectile/energy/excavate/weak
	armor = list(melee = 90, bullet = 90, laser = 90, energy = 90, bomb = 90, bio = 100, rad = 100)
	armor_soak = list(melee = 25, bullet = 25, laser = 25, energy = 25, bomb = 0, bio = 0, rad = 0)
	icon_state = "shielded_mining_mecha"
	shock_resist = 1
	var/attackcycle = 1

/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/do_special_attack(atom/A)
	. = TRUE // So we don't fire a bolt as well.
	switch(a_intent)
		if(I_DISARM) // Phase 3
			if(attackcycle == 1)
				phasethree_cycleone(A)
			else if(attackcycle == 2)
				phasethree_cycletwo(A)
			else
				phasethree_cyclethree(A)
		if(I_HURT) // Phase 1
			if(attackcycle == 1)
				phaseone_cycleone(A)
			else if(attackcycle == 2)
				phaseone_cycletwo(A)
			else
				phaseone_cyclethree(A)
		if(I_GRAB) // Phase 2
			if(attackcycle == 1)
				phasetwo_cycleone(A)
			else if(attackcycle == 2)
				phasetwo_cycletwo(A)
			else
				phasetwo_cyclethree(A)

//phase one
/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/proc/phaseone_cycleone(atom/target) //four seconds
	armor = list(melee = 90, bullet = 90, laser = 90, energy = 90, bomb = 90, bio = 100, rad = 100)
	armor_soak = list(melee = 25, bullet = 25, laser = 25, energy = 25, bomb = 0, bio = 0, rad = 0)
	icon_state = "shielded_mining_mecha"
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	sleep(10)
	upfour(target)
	leftfour(target)
	rightfour(target)
	downfour(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	sleep(10)
	upfour(target)
	leftfour(target)
	rightfour(target)
	downfour(target)
	sleep(10)
	attackcycle = 2


/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/proc/phaseone_cycletwo(atom/target) //four seconds
	armor = list(melee = 90, bullet = 90, laser = 90, energy = 90, bomb = 90, bio = 100, rad = 100)
	armor_soak = list(melee = 25, bullet = 25, laser = 25, energy = 25, bomb = 0, bio = 0, rad = 0)
	icon_state = "shielded_mining_mecha"
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	sleep(10)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	sleep(10)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	attackcycle = 3

/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/proc/phaseone_cyclethree(atom/target) //eight seconds where it's vunerable
	armor = list(melee = 50, bullet = 50, laser = 50, energy = 50, bomb = 50, bio = 100, rad = 100)
	armor_soak = list(melee = 0, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 0, rad = 0)
	icon_state = "mining_mecha"
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upfour_rightthree(target)
	upthree_rightfour(target)
	downfour_rightfour(target)
	downfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftfour(target)
	downfour_leftthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upfour_rightthree(target)
	upthree_rightfour(target)
	downfour_rightfour(target)
	downfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftfour(target)
	downfour_leftthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upfour_rightthree(target)
	upthree_rightfour(target)
	downfour_rightfour(target)
	downfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftfour(target)
	downfour_leftthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upfour_rightthree(target)
	upthree_rightfour(target)
	downfour_rightfour(target)
	downfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftfour(target)
	downfour_leftthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	attackcycle = 1

//phase two
/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/proc/phasetwo_cycleone(atom/target) //Seven seconds
	armor = list(melee = 90, bullet = 90, laser = 90, energy = 90, bomb = 90, bio = 100, rad = 100)
	armor_soak = list(melee = 25, bullet = 25, laser = 25, energy = 25, bomb = 0, bio = 0, rad = 0)
	icon_state = "shielded_mining_mecha"
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	sleep(10)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	downfour_leftfour(target)
	downthree_leftfour(target)
	downfour_leftthree(target)
	sleep(10)
	downfour(target)
	downfour_leftone(target)
	downfour_rightone(target)
	sleep(10)
	downfour_rightfour(target)
	downthree_rightfour(target)
	downfour_rightthree(target)
	sleep(10)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	sleep(10)
	upfour_rightfour(target)
	upthree_rightfour(target)
	upfour_rightthree(target)
	attackcycle = 2

/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/proc/phasetwo_cycletwo(atom/target) //Seven seconds
	armor = list(melee = 90, bullet = 90, laser = 90, energy = 90, bomb = 90, bio = 100, rad = 100)
	armor_soak = list(melee = 25, bullet = 25, laser = 25, energy = 25, bomb = 0, bio = 0, rad = 0)
	icon_state = "shielded_mining_mecha"
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	sleep(10)
	upfour_rightfour(target)
	upthree_rightfour(target)
	upfour_rightthree(target)
	sleep(10)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	sleep(10)
	downfour_rightfour(target)
	downthree_rightfour(target)
	downfour_rightthree(target)
	sleep(10)
	downfour(target)
	downfour_leftone(target)
	downfour_rightone(target)
	sleep(10)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	attackcycle = 3

/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/proc/phasetwo_cyclethree(atom/target) //seven seconds
	armor = list(melee = 50, bullet = 50, laser = 50, energy = 50, bomb = 50, bio = 100, rad = 100)
	armor_soak = list(melee = 0, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 0, rad = 0)
	icon_state = "mining_mecha"
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upthree_rightfour(target)
	upfour_rightthree(target)
	sleep(10)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	sleep(10)
	downfour_leftfour(target)
	downthree_leftfour(target)
	downfour_leftthree(target)
	downfour_rightfour(target)
	downthree_rightfour(target)
	downfour_rightthree(target)
	sleep(10)
	downfour(target)
	downfour_leftone(target)
	downfour_rightone(target)
	sleep(10)
	downfour_rightfour(target)
	downthree_rightfour(target)
	downfour_rightthree(target)
	sleep(10)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour_rightfour(target)
	upthree_rightfour(target)
	upfour_rightthree(target)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	attackcycle = 1

//phase three aka hard mode
/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/proc/phasethree_cycleone(atom/target) //seven seconds
	armor = list(melee = 90, bullet = 90, laser = 90, energy = 90, bomb = 90, bio = 100, rad = 100)
	armor_soak = list(melee = 25, bullet = 25, laser = 25, energy = 25, bomb = 0, bio = 0, rad = 0)
	icon_state = "shielded_mining_mecha"
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_leftone(target)
	downfour_rightone(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upthree_rightfour(target)
	upfour_rightthree(target)
	sleep(10)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	sleep(10)
	downfour_leftfour(target)
	downthree_leftfour(target)
	downfour_leftthree(target)
	downfour_rightfour(target)
	downthree_rightfour(target)
	downfour_rightthree(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_leftone(target)
	downfour_rightone(target)
	sleep(10)
	downfour_rightfour(target)
	downthree_rightfour(target)
	downfour_rightthree(target)
	sleep(10)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour_rightfour(target)
	upthree_rightfour(target)
	upfour_rightthree(target)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	attackcycle = 2

/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/proc/phasethree_cycletwo(atom/target) //seven seconds
	armor = list(melee = 90, bullet = 90, laser = 90, energy = 90, bomb = 90, bio = 100, rad = 100)
	armor_soak = list(melee = 25, bullet = 25, laser = 25, energy = 25, bomb = 0, bio = 0, rad = 0)
	icon_state = "shielded_mining_mecha"
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upfour_rightthree(target)
	upthree_rightfour(target)
	downfour_rightfour(target)
	downfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftfour(target)
	downfour_leftthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upfour_rightthree(target)
	upthree_rightfour(target)
	downfour_rightfour(target)
	downfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftfour(target)
	downfour_leftthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upfour_rightthree(target)
	upthree_rightfour(target)
	downfour_rightfour(target)
	downfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftfour(target)
	downfour_leftthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(10)
	upfour_leftfour(target)
	upfour_leftthree(target)
	upfour_leftthree(target)
	upfour_rightfour(target)
	upfour_rightthree(target)
	upthree_rightfour(target)
	downfour_rightfour(target)
	downfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftfour(target)
	downfour_leftthree(target)
	downthree_leftfour(target)
	sleep(10)
	upfour(target)
	upfour_rightone(target)
	upfour_leftone(target)
	downfour(target)
	downfour_rightone(target)
	downfour_leftone(target)
	rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	leftfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	attackcycle = 3

/mob/living/simple_mob/mechanical/mecha/eclipse/mining_guard/proc/phasethree_cyclethree(atom/target) //two seconds
	armor = list(melee = 50, bullet = 50, laser = 50, energy = 50, bomb = 50, bio = 100, rad = 100)
	armor_soak = list(melee = 0, bullet = 0, laser = 0, energy = 0, bomb = 0, bio = 0, rad = 0)
	icon_state = "mining_mecha"
	upfour_leftthree(target)
	upfour_lefttwo(target)
	upfour_leftone(target)
	upfour_rightone(target)
	upfour_righttwo(target)
	upfour_rightthree(target)
	upthree_rightfour(target)
	uptwo_rightfour(target)
	upone_rightfour(target)
	downone_rightfour(target)
	downtwo_rightfour(target)
	downthree_rightfour(target)
	downfour_rightthree(target)
	downfour_righttwo(target)
	downfour_rightone(target)
	downfour_leftone(target)
	downfour_lefttwo(target)
	downfour_leftthree(target)
	downthree_leftfour(target)
	downtwo_leftfour(target)
	downone_leftfour(target)
	upone_leftfour(target)
	uptwo_leftfour(target)
	upthree_leftfour(target)
	sleep(20)
	upfour_leftfour(target)
	upfour(target)
	upfour_rightfour(target)
	rightfour(target)
	downfour_rightfour(target)
	downfour(target)
	downfour_leftfour(target)
	leftfour(target)
	attackcycle = 1

//High overall defense, swaps between Burn and brute defense based off what was just used.
/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt //The final boss
	armor = list(melee = 60, bullet = 60, laser = 60, energy = 60, bomb = 80, bio = 100, rad = 100)
	specialattackprojectile = /obj/item/projectile/energy/plasma/vepr
	icon_state = "eclipse_janus"
	var/attackcycle = 1

/obj/item/projectile/energy/darkspike //This will end you
	name = "unknown_energy"
	icon = 'modular_chomp/icons/obj/guns/precursor/tyr.dmi'
	icon_state = "darkspike"
	damage = 50
	armor_penetration = 80
	speed = 15 //Note to self, may need to slow down even further.

/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/bullet_act(obj/item/projectile/P)
	.= ..()
	if(istype(P, /obj/item/projectile/bullet))
		armor = list(melee = 80, bullet = 80, laser = 40, energy = 40, bomb = 80, bio = 100, rad = 100)
		armor_soak = list(melee = 10, bullet = 10, laser = 0, energy = 0, bomb = 0, bio = 0, rad = 0)
		icon_state = "eclipse_janus_red"
	else
		armor = list(melee = 40, bullet = 40, laser = 80, energy = 80, bomb = 80, bio = 100, rad = 100)
		armor_soak = list(melee = 0, bullet = 0, laser = 10, energy = 10, bomb = 0, bio = 0, rad = 0)
		icon_state = "eclipse_janus_orange"

/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/do_special_attack(atom/A)
	. = TRUE // So we don't fire a bolt as well.
	switch(a_intent)
		if(I_DISARM) // Phase 3
			if(attackcycle == 1)
				phasethree_cycleone(A)
			else if(attackcycle == 2)
				phasethree_cycletwo(A)
			else
				phasethree_cyclethree(A)
		if(I_HURT) // Phase 1
			if(attackcycle == 1)
				phaseone_cycleone(A)
			else if(attackcycle == 2)
				phaseone_cycletwo(A)
			else
				phaseone_cyclethree(A)
		if(I_GRAB) // Phase 2
			if(attackcycle == 1)
				phasetwo_cycleone(A)
			else if(attackcycle == 2)
				phasetwo_cycletwo(A)
			else
				phasetwo_cyclethree(A)

//Phase One. Appears random but isn't. Scales higher.
/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/proc/phaseone_cycleone(atom/target)
	upfour_leftfour(target)
	sleep(5)
	downfour_rightfour(target)
	sleep(5)
	upfour_leftfour(target)
	sleep(5)
	downfour_leftfour(target)
	sleep(5)
	upfour_lefttwo(target)
	sleep(5)
	downfour_righttwo(target)
	sleep(5)
	upfour_lefttwo(target)
	sleep(5)
	downfour_lefttwo(target)
	sleep(5)
	uptwo_leftfour(target)
	sleep(5)
	downtwo_rightfour(target)
	sleep(5)
	uptwo_leftfour(target)
	sleep(5)
	downtwo_leftfour(target)
	sleep(5)
	upfour_leftone(target)
	sleep(5)
	downfour_rightone(target)
	sleep(5)
	upfour_leftone(target)
	sleep(5)
	downfour_leftone(target)
	sleep(5)
	upone_leftfour(target)
	sleep(5)
	downone_rightfour(target)
	sleep(5)
	upone_leftfour(target)
	sleep(5)
	downone_leftfour(target)
	sleep(5)
	upfour_leftthree(target)
	sleep(5)
	downfour_rightthree(target)
	sleep(5)
	upfour_leftthree(target)
	sleep(5)
	downfour_leftthree(target)
	sleep(5)
	upthree_leftfour(target)
	sleep(5)
	downthree_rightfour(target)
	sleep(5)
	upthree_leftfour(target)
	sleep(5)
	downthree_leftfour(target)
	sleep(5)
	upfour(target)
	sleep(5)
	rightfour(target)
	sleep(5)
	leftfour(target)
	sleep(5)
	downfour(target)
	attackcycle = 2

/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/proc/phaseone_cycletwo(atom/target)
	upfour_leftfour(target)
	downfour_rightfour(target)
	sleep(5)
	upfour_leftfour(target)
	downfour_leftfour(target)
	sleep(5)
	upfour_lefttwo(target)
	downfour_righttwo(target)
	sleep(5)
	upfour_lefttwo(target)
	downfour_lefttwo(target)
	sleep(5)
	uptwo_leftfour(target)
	downtwo_rightfour(target)
	sleep(5)
	uptwo_leftfour(target)
	downtwo_leftfour(target)
	sleep(5)
	upfour_leftone(target)
	downfour_rightone(target)
	sleep(5)
	upfour_leftone(target)
	downfour_leftone(target)
	sleep(5)
	upone_leftfour(target)
	downone_rightfour(target)
	sleep(5)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(5)
	upfour_leftthree(target)
	downfour_rightthree(target)
	sleep(5)
	upfour_leftthree(target)
	downfour_leftthree(target)
	sleep(5)
	upthree_leftfour(target)
	downthree_rightfour(target)
	sleep(5)
	upthree_leftfour(target)
	downthree_leftfour(target)
	sleep(5)
	upfour(target)
	rightfour(target)
	sleep(5)
	leftfour(target)
	downfour(target)
	attackcycle = 3

/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/proc/phaseone_cyclethree(atom/target)
	upfour_leftfour(target)
	downfour_rightfour(target)
	upfour_leftfour(target)
	downfour_leftfour(target)
	sleep(5)
	upfour_lefttwo(target)
	downfour_righttwo(target)
	upfour_lefttwo(target)
	downfour_lefttwo(target)
	sleep(5)
	uptwo_leftfour(target)
	downtwo_rightfour(target)
	uptwo_leftfour(target)
	downtwo_leftfour(target)
	sleep(5)
	upfour_leftone(target)
	downfour_rightone(target)
	upfour_leftone(target)
	downfour_leftone(target)
	sleep(5)
	upone_leftfour(target)
	downone_rightfour(target)
	upone_leftfour(target)
	downone_leftfour(target)
	sleep(5)
	upfour_leftthree(target)
	downfour_rightthree(target)
	upfour_leftthree(target)
	downfour_leftthree(target)
	sleep(5)
	upthree_leftfour(target)
	downthree_rightfour(target)
	upthree_leftfour(target)
	downthree_leftfour(target)
	sleep(5)
	upfour(target)
	rightfour(target)
	leftfour(target)
	downfour(target)
	attackcycle = 1

//Phase Two where we change things up a bit.
/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/proc/phasetwo_cycleone(atom/target) //shows a laser then fires a rockect
	Beam(target, icon_state = "sat_beam", time = 2.5 SECONDS, maxdistance = INFINITY)
	sleep(30)
	var/obj/item/projectile/P = new /obj/item/projectile/bullet/srmrocket(get_turf(src))
	P.launch_projectile(target, BP_TORSO, src)
	attackcycle = 2

/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/proc/phasetwo_cycletwo(atom/target) //summon the most useless horde
	new /mob/living/simple_mob/mechanical/hivebot/swarm/eclipse (src.loc)
	new /mob/living/simple_mob/mechanical/hivebot/swarm/eclipse (src.loc)
	new /mob/living/simple_mob/mechanical/hivebot/swarm/eclipse (src.loc)
	new /mob/living/simple_mob/mechanical/hivebot/swarm/eclipse (src.loc)
	new /mob/living/simple_mob/mechanical/hivebot/swarm/eclipse (src.loc)
	new /mob/living/simple_mob/mechanical/hivebot/swarm/eclipse (src.loc)
	new /mob/living/simple_mob/mechanical/hivebot/swarm/eclipse (src.loc)
	new /mob/living/simple_mob/mechanical/hivebot/swarm/eclipse (src.loc)
	attackcycle = 3

/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/proc/phasetwo_cyclethree(atom/target) //turns out the horde is meant to be a shield for the next attack.
	visible_message(span_warning("\The [src] begins to repair itself!"))
	sleep(20)
	adjustBruteLoss(-5)
	adjustFireLoss(-5)
	sleep(20)
	adjustBruteLoss(-5)
	adjustFireLoss(-5)
	sleep(20)
	adjustBruteLoss(-5)
	adjustFireLoss(-5)
	sleep(20)
	adjustBruteLoss(-5)
	adjustFireLoss(-5)
	sleep(20)
	adjustBruteLoss(-5)
	adjustFireLoss(-5)
	attackcycle = 1

//Phase three 2 wierd patterns, and 1 strange attack.
/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/proc/phasethree_cycleone(atom/target)
	specialattackprojectile = /obj/item/projectile/energy/darkspike
	upfour(target)
	downfour(target)
	sleep(2.5)
	upfour_leftone(target)
	upfour_rightone(target)
	downfour_leftone(target)
	downfour_rightone(target)
	sleep(2.5)
	upfour_lefttwo(target)
	upfour_righttwo(target)
	downfour_lefttwo(target)
	downfour_righttwo(target)
	sleep(2.5)
	upfour_leftthree(target)
	upfour_rightthree(target)
	downfour_leftthree(target)
	downfour_rightthree(target)
	sleep(2.5)
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_leftfour(target)
	downfour_rightfour(target)
	sleep(2.5)
	upthree_leftfour(target)
	upthree_rightfour(target)
	downthree_leftfour(target)
	downthree_rightfour(target)
	sleep(2.5)
	uptwo_leftfour(target)
	uptwo_rightfour(target)
	downtwo_leftfour(target)
	downtwo_rightfour(target)
	sleep(2.5)
	upone_leftfour(target)
	upone_rightfour(target)
	downone_leftfour(target)
	downone_rightfour(target)
	sleep(8)
	specialattackprojectile = /obj/item/projectile/scatter/shotgun
	leftfour(target)
	rightfour(target)
	attackcycle = 2

/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/proc/phasethree_cycletwo(atom/target)
	specialattackprojectile = /obj/item/projectile/energy/homing_bolt
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_leftfour(target)
	downfour_rightfour(target)
	sleep(5)
	upfour(target)
	downfour(target)
	leftfour(target)
	rightfour(target)
	attackcycle = 3

/mob/living/simple_mob/mechanical/mecha/eclipse/darkmatter_assualt/proc/phasethree_cyclethree(atom/target) //eight spinning death beams
	specialattackprojectile = /obj/item/projectile/energy/darkspike
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	sleep(2.5)
	upfour_leftthree(target)
	upthree_rightfour(target)
	downfour_rightthree(target)
	downthree_leftfour(target)
	sleep(2.5)
	upfour_lefttwo(target)
	uptwo_rightfour(target)
	downfour_righttwo(target)
	downtwo_leftfour(target)
	sleep(2.5)
	upfour_leftone(target)
	upone_rightfour(target)
	downfour_rightone(target)
	downone_leftfour(target)
	sleep(2.5)
	upfour(target)
	rightfour(target)
	downfour(target)
	leftfour(target)
	sleep(2.5)
	upfour_rightone(target)
	downone_rightfour(target)
	downfour_leftone(target)
	upone_leftfour(target)
	sleep(2.5)
	upfour_righttwo(target)
	downtwo_rightfour(target)
	downfour_lefttwo(target)
	uptwo_leftfour(target)
	sleep(2.5)
	upfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftthree(target)
	upthree_leftfour(target)
	sleep(2.5)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	upfour_leftfour(target)
	sleep(2.5) //Now we reverse
	upfour_rightthree(target)
	downthree_rightfour(target)
	downfour_leftthree(target)
	upthree_leftfour(target)
	sleep(2.5)
	upfour_righttwo(target)
	downtwo_rightfour(target)
	downfour_lefttwo(target)
	uptwo_leftfour(target)
	sleep(2.5)
	upfour_rightone(target)
	downone_rightfour(target)
	downfour_leftone(target)
	upone_leftfour(target)
	sleep(2.5)
	upfour(target)
	rightfour(target)
	downfour(target)
	leftfour(target)
	sleep(2.5)
	upfour_leftone(target)
	upone_rightfour(target)
	downfour_rightone(target)
	downone_leftfour(target)
	sleep(2.5)
	upfour_lefttwo(target)
	uptwo_rightfour(target)
	downfour_righttwo(target)
	downtwo_leftfour(target)
	sleep(2.5)
	upfour_leftthree(target)
	upthree_rightfour(target)
	downfour_rightthree(target)
	downthree_leftfour(target)
	sleep(2.5)
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	attackcycle = 1

/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss
	name = "Tyr Guard Drone"
	armor = list(melee = 40, bullet = 40, laser = 40, energy = 40, bomb = 80, bio = 100, rad = 100)
	specialattackprojectile = /obj/item/projectile/energy/plasma/vepr
	icon_state = "secert_boss"
	hovering = TRUE
	health = 1000
	maxHealth = 1000
	shock_resist = 1
	loot_list = list(/obj/item/gun/energy/weatherbombardment = 100)
	var/attackcycle = 0

/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss/do_special_attack(atom/A)
	if(attackcycle == 1)
		attackone(A)
	else if(attackcycle == 2)
		attacktwo(A)
	else if(attackcycle == 3)
		attackthree(A)
	else if(attackcycle == 4)
		attackfour(A)
	else if(attackcycle == 5)
		attackfive(A)
	else if(attackcycle == 6)
		attacksix(A)
	else if(attackcycle == 7)
		attackseven(A)
	else if(attackcycle == 8)
		attackeight(A)
	else
		if(prob(50))
			attackcycle = 8
		else
			attackcycle = 1

/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss/proc/attackone(atom/target) //get behind a pillar or suffer
	Beam(target, icon_state = "solar_beam", time = 2.5 SECONDS, maxdistance = INFINITY)
	var/obj/item/projectile/P = new /obj/item/projectile/beam/heavylaser(get_turf(src))
	sleep(30)
	P.launch_projectile(target, BP_TORSO, src)
	if(prob(50))
		attackcycle = 2
	else
		attackcycle = 3


/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss/proc/attacktwo(atom/target) //Fires off artlillery in cross
	specialattackprojectile = /obj/item/projectile/arc/fragmentation/metoerstrike
	upfour(target)
	downfour(target)
	leftfour(target)
	rightfour(target)
	if(prob(50))
		attackcycle = 4
	else
		attackcycle = 5

/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss/proc/attackthree(atom/target) //Fires off artlillery in an X
	specialattackprojectile = /obj/item/projectile/arc/fragmentation/metoerstrike
	upfour_leftfour(target)
	upfour_rightfour(target)
	downfour_rightfour(target)
	downfour_leftfour(target)
	if(prob(50))
		attackcycle = 4
	else
		attackcycle = 5

/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss/proc/attackfour(atom/target)
	Beam(target, icon_state = "solar_beam", time = 2.5 SECONDS, maxdistance = INFINITY)
	var/obj/item/projectile/P = new /obj/item/projectile/bullet/dragon(get_turf(src))
	sleep(30)
	P.launch_projectile(target, BP_TORSO, src)
	if(prob(50))
		attackcycle = 6
	else
		attackcycle = 7

/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss/proc/attackfive(atom/target)
	Beam(target, icon_state = "solar_beam", time = 2.5 SECONDS, maxdistance = INFINITY)
	var/obj/item/projectile/P = new /obj/item/projectile/arc/fragmentation/metoerstrike(get_turf(src))
	sleep(30)
	P.launch_projectile(target, BP_TORSO, src)
	if(prob(50))
		attackcycle = 6
	else
		attackcycle = 7

/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss/proc/attacksix(atom/target)
	specialattackprojectile = /obj/item/projectile/energy/spikeenergy_ball/slow
	upfour(target)
	downfour(target)
	sleep(5)
	upfour_rightone(target)
	downfour_leftone(target)
	sleep(5)
	upfour_righttwo(target)
	downfour_lefttwo(target)
	sleep(5)
	upfour_rightthree(target)
	downfour_leftthree(target)
	sleep(5)
	upfour_rightfour(target)
	downfour_leftfour(target)
	specialattackprojectile = /obj/item/projectile/arc/fragmentation/metoerstrike
	upfour_leftfour(target)
	downfour_rightfour(target)
	sleep(5)
	specialattackprojectile = /obj/item/projectile/energy/spikeenergy_ball/slow
	upthree_rightfour(target)
	downthree_leftfour(target)
	sleep(5)
	uptwo_rightfour(target)
	downtwo_leftfour(target)
	sleep(5)
	upone_rightfour(target)
	downone_leftfour(target)
	sleep(5)
	rightfour(target)
	leftfour(target)
	specialattackprojectile = /obj/item/projectile/arc/fragmentation/metoerstrike
	upfour(target)
	downfour(target)
	sleep(5)
	specialattackprojectile = /obj/item/projectile/energy/spikeenergy_ball/slow
	downone_rightfour(target)
	upone_leftfour(target)
	sleep(5)
	downtwo_rightfour(target)
	uptwo_leftfour(target)
	sleep(5)
	downthree_rightfour(target)
	upthree_leftfour(target)
	sleep(5)
	downfour_rightfour(target)
	upfour_leftfour(target)
	specialattackprojectile = /obj/item/projectile/arc/fragmentation/metoerstrike
	upfour_rightfour(target)
	downfour_leftfour(target)
	sleep(5)
	specialattackprojectile = /obj/item/projectile/energy/spikeenergy_ball/slow
	downfour_rightthree(target)
	upfour_leftthree(target)
	sleep(5)
	downfour_righttwo(target)
	upfour_lefttwo(target)
	sleep(5)
	downfour_rightone(target)
	upfour_leftone(target)
	sleep(5)
	upfour(target)
	downfour(target)
	leftfour(target)
	rightfour(target)
	if(prob(50))
		attackcycle = 8
	else
		attackcycle = 1

/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss/proc/attackseven(atom/target)
	specialattackprojectile = /obj/item/projectile/energy/spikeenergy_ball/slow
	for(var/i =1 to 3)
		upfour_leftfour(target)
		upfour_rightfour(target)
		downfour_rightfour(target)
		downfour_leftfour(target)
		sleep(2.5)
		upfour_leftthree(target)
		upthree_rightfour(target)
		downfour_rightthree(target)
		downthree_leftfour(target)
		sleep(2.5)
		upfour_lefttwo(target)
		uptwo_rightfour(target)
		downfour_righttwo(target)
		downtwo_leftfour(target)
		sleep(2.5)
		upfour_leftone(target)
		upone_rightfour(target)
		downfour_rightone(target)
		downone_leftfour(target)
		sleep(2.5)
		upfour(target)
		rightfour(target)
		downfour(target)
		leftfour(target)
		sleep(2.5)
		upfour_rightone(target)
		downone_rightfour(target)
		downfour_leftone(target)
		upone_leftfour(target)
		sleep(2.5)
		upfour_righttwo(target)
		downtwo_rightfour(target)
		downfour_lefttwo(target)
		uptwo_leftfour(target)
		sleep(2.5)
		upfour_rightthree(target)
		downthree_rightfour(target)
		downfour_leftthree(target)
		upthree_leftfour(target)
		sleep(2.5)
		upfour_rightfour(target)
		downfour_rightfour(target)
		downfour_leftfour(target)
		upfour_leftfour(target)
	if(prob(50))
		attackcycle = 8
	else
		attackcycle = 1

/mob/living/simple_mob/mechanical/mecha/eclipse/precursor_boss/proc/attackeight(atom/target) //very fast beam but low punishment
	Beam(target, icon_state = "sat_beam", time = 2 SECONDS, maxdistance = INFINITY)
	var/obj/item/projectile/P = new /obj/item/projectile/scatter/laser(get_turf(src))
	sleep(25)
	P.launch_projectile(target, BP_TORSO, src)
	if(prob(50))
		attackcycle = 2
	else
		attackcycle = 3