// Gas
#define REAGENT_MIASMA "Miasma"
#define REAGENT_ID_MIASMA "miasma"

// Drugs
#define REAGENT_CLEANSINGAGENT "Cleansing Agent"
#define REAGENT_ID_CLEANSINGAGENT "cleansingagent"
#define REAGENT_PURIFYINGAGENT "Purifying Agent"
#define REAGENT_ID_PURIFYINGAGENT "purifyingagent"
#define REAGENT_BURNCARD "Burning Bicaridine"
#define REAGENT_ID_BURNCARD "burncard"
#define REAGENT_FLAMECURE "Flame Cure"
#define REAGENT_ID_FLAMECURE "flamecure"
#define REAGENT_NEOTANE "Neo Kelotane"
#define REAGENT_ID_NEOTANE "neotane"
#define REAGENT_BLOODSEALER "Blood Sealer"
#define REAGENT_ID_BLOODSEALER "bloodsealer"
#define REAGENT_LIVINGAGENT "Living Agent"
#define REAGENT_ID_LIVINGAGENT "livingagent"
#define REAGENT_PERFORMANCEPEAKER "Performance Peaker"
#define REAGENT_ID_PERFORMANCEPEAKER "performancepeaker"
#define REAGENT_SOULDEW "Soul Dew"
#define REAGENT_ID_SOULDEW "souldew"
#define REAGENT_QUADCORD "Quadcord"
#define REAGENT_ID_QUADCORD "quadcord"
#define REAGENT_JUGGERNOG "Juggernog"
#define REAGENT_ID_JUGGERNOG "juggernog"
#define REAGENT_CUREA "Curea"
#define REAGENT_ID_CUREA "curea"
#define REAGENT_LIQUIDHEALER "Liquid Healer"
#define REAGENT_ID_LIQUIDHEALER "liquidhealer"
#define REAGENT_PHOENIXBREATH "Phoenix Breath"
#define REAGENT_ID_PHOENIXBREATH "phoenixbreath"
#define REAGENT_DRYAGENT "Dry Agent"
#define REAGENT_ID_DRYAGENT "dryagent"
#define REAGENT_APHRODISIAC "Aphrodisiac"
#define REAGENT_ID_APHRODISIAC "aphrodisiac"
#define REAGENT_SORBITOL "Sorbitol"
#define REAGENT_ID_SORBITOL "sorbitol"
#define REAGENT_CLARIDYL "Claridyl Natural Remedy"
#define REAGENT_ID_CLARIDYL "claridyl"
#define REAGENT_DYLOTEANE "The Anti-Irish"
#define REAGENT_ID_DYLOTEANE "dyloteane"
#define REAGENT_BLOODBURN "Bloodburn"
#define REAGENT_ID_BLOODBURN "bloodburn"
#define REAGENT_EDEN "Eden"
#define REAGENT_ID_EDEN "eden"
#define REAGENT_EDENSNAKE "Tainted Eden"
#define REAGENT_ID_EDENSNAKE "eden_snake"
#define REAGENT_TERCOZOLAM "Tercozolam"
#define REAGENT_ID_TERCOZOLAM "tercozolam"
#define REAGENT_HANNOA "Hannoa"
#define REAGENT_ID_HANNOA "hannoa"
#define REAGENT_BULLVALENE "bullvalene"
#define REAGENT_ID_BULLVALENE "bullvalene"
#define REAGENT_SERAZINE "Serazine"
#define REAGENT_ID_SERAZINE "serazine"
#define REAGENT_ALIZENE "Alizene"
#define REAGENT_ID_ALIZENE "alizene"

// Food & Drinks
#define REAGENT_SNAPS "Akvavit"
#define REAGENT_ID_SNAPS "snaps"
#define REAGENT_MATCHALATTE "Matcha latte"
#define REAGENT_ID_MATCHALATTE "matcha_latte"
#define REAGENT_TEALEAVESGREEN  "Green tea leaves"
#define REAGENT_ID_TEALEAVESGREEN "tealeavesgreen"
#define REAGENT_BLONDIEMIX "Blondie Mix"
#define REAGENT_ID_BLONDIEMIX "blondiemix"
#define REAGENT_CHERRYTEA "Cherry Tea"
#define REAGENT_ID_CHERRYTEA "cherrytea"
#define REAGENT_WATERMELONTEA "Watermelon Tea"
#define REAGENT_ID_WATERMELONTEA "watermelontea"
#define REAGENT_SLIMEDRINK "Slime"
#define REAGENT_ID_SLIMEDRINK "slimedrink"
#define REAGENT_SPIDERDRINK "Brimming glass of spiders"
#define REAGENT_ID_SPIDERDRINK "spiderdrink"
#define REAGENT_BLUETRAIN "blue train"
#define REAGENT_ID_BLUETRAIN "bluetrain"
#define REAGENT_LOWPOWER "The low power"
#define REAGENT_ID_LOWPOWER "lowpower"
#define REAGENT_HIGHPOWER "The High power"
#define REAGENT_ID_HIGHPOWER "highpower"
#define REAGENT_JACKBREW "Rush hour"
#define REAGENT_ID_JACKBREW "jackbrew"
#define REAGENT_BOOKWYRM "Bookwyrm's bite"
#define REAGENT_ID_BOOKWYRM "bookwyrm"
#define REAGENT_FLAPPER "Flapper"
#define REAGENT_ID_FLAPPER "flapper"
#define REAGENT_OILSLIDE "Oil slide"
#define REAGENT_ID_OILSLIDE "oilslide"
#define REAGENT_SITONMYFACE "Sit on my face"
#define REAGENT_ID_SITONMYFACE "sitonmyface"
#define REAGENT_HACHI "Hachi"
#define REAGENT_ID_HACHI "hachi"
#define REAGENT_FRESHTEA "Refreshing tea"
#define REAGENT_ID_FRESHTEA "freshtea"
#define REAGENT_FRESHGREENTEA "Refreshing green tea"
#define REAGENT_ID_FRESHTEAGREEN "freshteagreen"
#define REAGENT_TEAMUSH "Tea mush"
#define REAGENT_ID_TEAMUSH "teamush"
#define REAGENT_INSTANTTEAPOWDERGREEN "Instant green tea powder"
#define REAGENT_ID_INSTANTTEAPOWDERGREEN "instantteapowdergreen"
#define REAGENT_INSTANTTEAGREEN "Instant green tea"
#define REAGENT_ID_INSTANTTEAGREEN "instantteagreen"
#define REAGENT_MATCHAPOWDER "Matcha powder"
#define REAGENT_ID_MATCHAPOWDER "matchapowder"
#define REAGENT_MATCHA "Matcha"
#define REAGENT_ID_MATCHA "matcha"
#define REAGENT_BUBBLETEAWATERMELON "Watermelon bubble tea"
#define REAGENT_ID_BUBBLETEAWATERMELON "bubbleteawatermelon"
#define REAGENT_BUBBLETEASTRAWBERRY "Strawberry bubble tea"
#define REAGENT_ID_BUBBLETEASTRAWBERRY "bubbleteastrawberry"
#define REAGENT_BUBBLETEACHERRY "Cherry bubble tea"
#define REAGENT_ID_BUBBLETEACHERRY "bubbleteacherry"
#define REAGENT_BUBBLETEACOFFEE "Coffee bubble tea"
#define REAGENT_ID_BUBBLETEACOFFEE "bubbleteacoffee"
#define REAGENT_BUBBLETEABANANA "Banana bubble tea"
#define REAGENT_ID_BUBBLETEABANANA "bubbleteabanana"
#define REAGENT_HORCHATA "Horchata"
#define REAGENT_ID_HORCHATA "horchata"
#define REAGENT_NARSOUR "Nar'Sour"
#define REAGENT_ID_NARSOUR "narsour"
#define REAGENT_COGCHAMP "CogChamp"
#define REAGENT_ID_COGCHAMP "cogchamp"
#define REAGENT_ARACHNIDSLAMMER "Arachnid Slammer"
#define REAGENT_ID_ARACHNIDSLAMMER "arachnidslammer"
#define REAGENT_INFUSEDARACHNIDSLAMMER "Infused Arachnid Slammer"
#define REAGENT_ID_INFUSEDARACHNIDSLAMMER "infusedarachnidslammer"
#define REAGENT_ENRAGEDARACHNIDSLAMMER "Enraged Arachnid Slammer"
#define REAGENT_ID_ENRAGEDARACHNIDSLAMMER "enragedarachnidslammer"
#define REAGENT_PILK "Pilk"
#define REAGENT_ID_PILK "pilk"
#define REAGENT_FETCHINGFIZZ "Fetching Fizz"
#define REAGENT_ID_FETCHINGFIZZ "fetching_fizz"
#define REAGENT_HEARTYPUNCH "Hearty Punch"
#define REAGENT_ID_HEARTYPUNCH "hearty_punch"
#define REAGENT_SQUIRTCIDER "Squirt Cider"
#define REAGENT_ID_SQUIRTCIDER "squirt_cider"
#define REAGENT_FRINGEWEAVER "Fringe Weaver"
#define REAGENT_ID_FRINGEWEAVER "fringe_weaver"
#define REAGENT_CREVICESPIKE "Crevice Spike"
#define REAGENT_ID_CREVICESPIKE "crevice_spike"
#define REAGENT_DUPLEX "Duplex"
#define REAGENT_ID_DUPLEX "duplex"
#define REAGENT_MAUNALOA "Mauna Loa"
#define REAGENT_ID_MAUNALOA "mauna_loa"
#define REAGENT_HIVEMINDERASER "Hivemind Eraser"
#define REAGENT_ID_HIVEMINDERASER "hiveminderaser"
#define REAGENT_WORMBLOOD "Worm Blood"
#define REAGENT_ID_WORMBLOOD "wormblood"


// Modifiers
#define REAGENT_ENERGYBOOSTER "Energy Booster"
#define REAGENT_ID_ENERGYBOOSTER "energybooster"
#define REAGENT_OCEANICCURE "Oceanic Cure"
#define REAGENT_ID_OCEANICCURE "oceaniccure"
#define REAGENT_DEATHCLAWMUTAGEN "Deathclaw Mutagen"
#define REAGENT_ID_DEATHCLAWMUTAGEN "deathclawmutagen"
#define REAGENT_SENSEENHANCER "Sense Enhancer"
#define REAGENT_ID_SENSEENHANCER "senseenhancer"
#define REAGENT_HEATNULLIFER "Heat Nullifer"
#define REAGENT_ID_HEATNULLIFER "heatnullifer"


// Other
#define REAGENT_PURPLESAP "purplesap"
#define REAGENT_ID_PURPLESAP "Purple sap"
#define REAGENT_BLUESAP "Blue Sap"
#define REAGENT_ID_BLUESAP "bluesap"
#define REAGENT_ORANGESAP "Orange sap"
#define REAGENT_ID_ORANGESAP "orangesap"
#define REAGENT_NITRATE "Nitrate"
#define REAGENT_ID_NITRATE "nitrate"
#define REAGENT_ALUMINUMNITRATE "Aluminum Nitrate"
#define REAGENT_ID_ALUMINUMNITRATE "aluminum_nitrate"
#define REAGENT_SPIDEREGG "spider eggs"
#define REAGENT_ID_SPIDEREGG "spideregg"
#define REAGENT_PITCHERNECTAR "Pitcher Nectar"
#define REAGENT_ID_PITCHERNECTAR "pitcher_nectar"
#define REAGENT_BENZILATE  "Odd Goo"
#define REAGENT_ID_BENZILATE "benzilate"
#define REAGENT_PHENETHYLAMINE "Phenethylamine"
#define REAGENT_ID_PHENETHYLAMINE "phenethylamine"
#define REAGENT_XEYAKIN_BLOOD "Xeyakin Blood"
#define REAGENT_ID_XEYAKIN_BLOOD "xeyakinblood"


// Phoronreagents
#define REAGENT_TARTRATE "Chlorified Tartrate"
#define REAGENT_ID_TARTRATE "tartrate"
#define REAGENT_BICORDRAZINE "Bicordrazine"
#define REAGENT_ID_BICORDRAZINE "bicordrazine"
#define REAGENT_GENEDRAZINE "Genedrazine"
#define REAGENT_ID_GENEDRAZINE "genedrazine"
#define REAGENT_LACERTUSOL "Lacertusol"
#define REAGENT_ID_LACERTUSOL "lacertusol"
#define REAGENT_MUTAGENX "Extreme Mutagen"
#define REAGENT_ID_MUTAGENX "mutagen_x"
#define REAGENT_UNKNOWN "Unanalyzed Reagent"
#define REAGENT_ID_UNKNOWN "unknown"
#define REAGENT_AMORAPOTIO "Amorapotio"
#define REAGENT_ID_AMORAPOTIO "amorapotio"
#define REAGENT_NASTY "Nasty"
#define REAGENT_ID_NASTY "nasty"
#define REAGENT_BABELIZINE "Babelizine"
#define REAGENT_ID_BABELIZINE "babelizine"
#define REAGENT_CALCISOL "Calcisol"
#define REAGENT_ID_CALCISOL "calcisol"
#define REAGENT_MALAXITOL "Malaxitol"
#define REAGENT_ID_MALAXITOL "malaxitol"
#define REAGENT_PARALITOL "Paralitol"
#define REAGENT_ID_PARALITOL "paralitol"
#define REAGENT_DOLORAN "Doloran"
#define REAGENT_ID_DOLORAN "doloran"
#define REAGENT_FULGURACIN "Fulguracin"
#define REAGENT_ID_FULGURACIN "fulguracin"
#define REAGENT_MORTEMOL "Mortemol"
#define REAGENT_ID_MORTEMOL "mortemol"
#define REAGENT_TEGOXANE "Tegoxane"
#define REAGENT_ID_TEGOXANE "tegoxane"
#define REAGENT_EXPULSICOL "Expulsicol"
#define REAGENT_ID_EXPULSICOL "expulsicol"
#define REAGENT_OCULUSOSONE "Oculusosone"
#define REAGENT_ID_OCULUSOSONE "oculusosone"
#define REAGENT_DESTITUTIONECAM "Destitutionecam"
#define REAGENT_ID_DESTITUTIONECAM "destitutionecam"
#define REAGENT_SAPOFORMATOR "Sapoformator"
#define REAGENT_ID_SAPOFORMATOR "sapoformator"
#define REAGENT_RADX "Rad-X"
#define REAGENT_ID_RADX "rad_x"
#define REAGENT_CALORAN "Caloran"
#define REAGENT_ID_CALORAN "caloran"
#define REAGENT_THESTUFF "The Stuff"
#define REAGENT_ID_THESTUFF "the_stuff"
#define REAGENT_FRIOLINE "Frioline"
#define REAGENT_ID_FRIOLINE "frioline"
#define REAGENT_LUXITOL "Luxitol"
#define REAGENT_ID_LUXITOL "luxitol"
#define REAGENT_LIQUIDSKIN "Liquid Skin"
#define REAGENT_ID_LIQUIDSKIN "liquid_skin"
#define REAGENT_ENERGIZEDPHORON "Energized Phoron"
#define REAGENT_ID_ENERGIZEDPHORON "energized_phoron"
#define REAGENT_INDUROMOL "Induromol"
#define REAGENT_ID_INDUROMOL "induromol"
#define REAGENT_OBSCURITOL "Obscuritol"
#define REAGENT_ID_OBSCURITOL "obscuritol"
#define REAGENT_OXYPHOROMIN "Oxyphoromin"
#define REAGENT_ID_OXYPHOROMIN "oxyphoromin"
#define REAGENT_LIQUIDBLUESPACE "Liquid Bluespace"
#define REAGENT_ID_LIQUIDBLUESPACE "liquid_bluespace"
#define REAGENT_GASEOUSDEATH "Gaseous Death"
#define REAGENT_ID_GASEOUSDEATH "gaseous_death"
#define REAGENT_OCCAECOSONE "Occaecosone"
#define REAGENT_ID_OCCAECOSONE "occaecosone"
#define REAGENT_IGNISOL "Ignisol"
#define REAGENT_ID_IGNISOL "ignisol"
#define REAGENT_PHORONICACID "Phoronic acid"
#define REAGENT_ID_PHORONICACID "phoronic_acid"
#define REAGENT_NOCTURNOL "Nocturnal"
#define REAGENT_ID_NOCTURNOL "nocturnol"


// Toxins
#define REAGENT_DEATHBLOOD "Irradiating Blood"
#define REAGENT_ID_DEATHBLOOD "deathblood"
#define REAGENT_LIQUIDFIRE "Liquid Fire"
#define REAGENT_ID_LIQUIDFIRE "liquidfire"
#define REAGENT_NEOLIQUIDFIRE "Neon Liquid Fire"
#define REAGENT_ID_NEOLIQUIDFIRE "neoliquidfire"
#define REAGENT_LIQUIDLIFE "Liquid Life"
#define REAGENT_ID_LIQUIDLIFE "liquidlife"

#define REAGENT_NUMBING_FLUID "Numbing Fluid"
#define REAGENT_ID_NUMBING_FLUID "succubi_numbing"
#define REAGENT_PARALYZE_FLUID "Paralyzing Fluid"
#define REAGENT_ID_PARALYZE_FLUID "succubi_paralize"
#define REAGENT_ID_APHRODIAC_FLUID "succubi_aphrodisiac"
