#define NO_AUTO_LOAD 0
#define OPEN_BOLT 1
#define CLOSED_BOLT 2
#define LOCK_OPEN_EMPTY 4
#define LOCK_MANUAL_LOCK 8
#define LOCK_SLAPPABLE 16
#define CHAMBER_ON_RELOAD 32

#define INTERNAL_MAG_SEPARATE 1
#define IS_PUMP_SHOTGUN 2
